use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ZQSwiftTools_Example' do
  pod 'ZQSwiftTools', :path => '../'

  target 'ZQSwiftTools_Tests' do
    inherit! :search_paths

    
  end
end
